name: people_index
description: A mobile app to index popular people in the movies industry.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  go_router: ^3.1.1
  injectable: ^1.5.3
  get_it: ^7.2.0
  dio: ^4.0.6
  retrofit: ^3.0.1+1
  drift: ^1.6.0
  sqlite3_flutter_libs: ^0.5.7
  path_provider: ^2.0.10
  path: ^1.8.1
  freezed: ^2.0.3+1
  dartz: ^0.10.1
  equatable: ^2.0.3
  tuple: ^2.0.0
  flutter_hooks: ^0.18.4
  cached_network_image: ^3.2.1
  readmore: ^2.1.0
  gallery_saver: ^2.3.2
  internet_connection_checker: ^0.0.1+4
  shared_preferences: ^2.0.15

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.0
  retrofit_generator: ^4.0.1
  drift_dev: ^1.6.0
  injectable_generator:
  build_runner:
  flutter_native_splash: ^2.2.3
  logger: ^1.1.0
  freezed_annotation: ^2.0.3

flutter:
  uses-material-design: true
  generate: true
  assets:
    - config/app_config.json

flutter_intl:
  enabled: true

